ALTER TABLE public.etiquetas_plantillas
ADD COLUMN IF NOT EXISTS papel_nombre TEXT NOT NULL DEFAULT 'A4',
ADD COLUMN IF NOT EXISTS papel_ancho_mm NUMERIC(6,2) NOT NULL DEFAULT 210,
ADD COLUMN IF NOT EXISTS papel_alto_mm NUMERIC(6,2) DEFAULT 297;
